name: Create PR to main-ee

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.UPSTREAM_REPO_SECRET }}
          INTERNAL_API_URL: ${{ secrets.INTERNAL_API_URL }}
          INTERNAL_API_TOKEN: ${{ secrets.INTERNAL_API_TOKEN }}
        run: |
          # 检查是否已经存在从 main 到 main-ee 的 PR
          existing_pr=$(gh pr list --base main-ee --head main --json number --jq '.[0].number')

          if [ -z "$existing_pr" ]; then
            # 如果不存在，创建新的 PR
            new_pr=$(gh pr create --base main-ee --head main \
              --title "Sync main to main-ee" \
              --body "Automatically created PR to sync changes from main to main-ee")
            
            # 发送内部消息
            # curl -X POST $INTERNAL_API_URL \
            #   -H "Authorization: Bearer $INTERNAL_API_TOKEN" \
            #   -H "Content-Type: application/json" \
            #   -d '{"message": "New PR created: main to main-ee", "pr_url": "'"$new_pr"'"}'
            
          else
            echo "A PR from main to main-ee already exists (PR #$existing_pr). Checking for conflicts..."
            
            # 检查是否有冲突
            conflicts=$(gh pr view $existing_pr --json mergeStateStatus --jq '.mergeStateStatus')
            
            if [ "$conflicts" = "CONFLICTING" ]; then
              echo "Conflicts detected. Creating new branch and PR..."
              
              # 创建新分支
              new_branch="sync-main-to-main-ee-$(date +%Y%m%d%H%M%S)"
              git checkout -b $new_branch
              git push origin $new_branch
              
              # 创建新的 PR
              new_pr=$(gh pr create --base main-ee --head $new_branch \
                --title "Sync main to main-ee (resolved conflicts)" \
                --body "Automatically created PR to sync changes from main to main-ee. This PR was created to resolve conflicts.")
              
              # 关闭旧的 PR
              gh pr close $existing_pr --comment "Closing due to conflicts. New PR created: $new_pr"
              
              # 发送内部消息
              # curl -X POST $INTERNAL_API_URL \
              #   -H "Authorization: Bearer $INTERNAL_API_TOKEN" \
              #   -H "Content-Type: application/json" \
              #   -d '{"message": "Conflicts detected in main to main-ee PR. New PR created to resolve conflicts.", "pr_url": "'"$new_pr"'"}'
            else
              echo "Existing PR has no conflicts."
            fi
          fi
